### ISSUE TITLE
about z-axis

### ISSUE THREAD

**Issue by akbkon** [ibaiGorordo/AWR1642-Read-Data-Python-MMWAVE-SDK-2#26]
hello!

My problem is that when I use AWR1642 to collect data, the value of z[objectNum] is always being 0. Could you please tell me what I can do to solve the problem?

Hope for your reply! Thanks!

**Comment by ibaiGorordo** [comment]
Hello,

If you are using the normal AWR1642 BOOST, it only measures the 2D position, that is why the Z value is 0. You will have to use another board like the AWR1843 for the 3D point cloud.

Regards,
Ibai

**Comment by akbkon** [comment]
Oh, I see. I really appreciate for your help!
