### ISSUE TITLE
Left and right reversed

### ISSUE THREAD

**Issue by bluems** [ibaiGorordo/AWR1642-Read-Data-Python-MMWAVE-SDK-2#32]
Hi,

I use the board based on IWR1642, Ubuntu 20.04 and Python 3.8.
When I use your code, The data your code has responded to will appear reversed left and right.
Compared to TI's official demo(mmWave_Demo_Visualizer), it looks reversed.

I tested readData_AWR1642.py

**Comment by ibaiGorordo** [comment]
Hi, 

you just need to modify [line 287](https://github.com/ibaiGorordo/AWR1642-Read-Data-Python-MMWAVE-SDK-2/blob/412464715045a55da2310d93ae0f8a8a22afcd6b/readData_AWR1642.py#L287) to:

```
x = detObj["x"]
```

**Comment by bluems** [comment]
thanks your answer!
